### ISSUE TITLE
How can I use hand_tracking with my webcam?

### ISSUE THREAD

**Issue by ghost** [JuliaPoo/MultiHand-Tracking#1]
Hi @JuliaPoo  thank you very much for this mediapipe wrapper for python!
I have a pretty noob question, I am new to this environment and I would like to use my webcam to use the hand tracker, is this possible? You think you could upload a mini example :( I've been trying using videocapture from OpenCV, but it didn't work for me.

**Comment by JuliaPoo** [comment]
Hi! If you intended to use this for real time purposes, i don't sugest you do that as this python implementation is just below realtime (maybe 4-8fps). My intention for this is just for quick prototyping since python is way easier to build on than google's mediapipe implementation. 

However, if you want to make it work with webcam, you can initialise a MultiHandTracker instance with the flag independent=False and sequentially call the instance with images from the webcam.

**Comment by ghost** [comment]
can you help me in a simple code for video capture using webcam, I tried too much all time give me an error in returned values
